version: '1'

services:
  app:
    image: rglomski/pairing-challenge:latest
    volumes:
      - .:/app
      - .bash_history:/root/.bash_history
      - node_modules:/app/node_modules
    tmpfs:
      - /app/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"

volumes:
  node_modules:
